require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - "gemfiles/**/*"
    - "vendor/**/*"


## Layout ######################################################################

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 120

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

## Metrics #####################################################################

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']

Metrics/ModuleLength:
  CountAsOne: ['array', 'hash', 'heredoc', 'method_call']

## Style #######################################################################

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/RegexpLiteral:
  EnforcedStyle: percent_r

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/SafeNavigation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/YodaCondition:
  Enabled: false

## RSpec ########################################################################
RSpec/ExampleLength:
  Max: 7
  Enabled: false

RSpec/MultipleExpectations:
  Max: 2
  Enabled: false
